### ISSUE TITLE
Destructering is really nice!

### ISSUE THREAD

**Issue by Cascuna** [heerhaan/Marvin-the-Astronaut#6]
https://github.com/heerhaan/Marvin-the-Astronaut/blob/master/myBot.js#L19
Here you have 
`
let age = args[0]; // Remember arrays are 0-based!.
 let sex = args[1];
 let location = args[2];`
But, in Ecmascript 6 (new version of javascript) you can do
`let [age, sex, location] = args` which does the same thing as the code above! 
More about destructering https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Operatoren/Destructuring_assignment

**Comment by heerhaan** [comment]
@Cascuna Ik hou zoveel van je, en ik zie dit allemaal nu pas.

**Comment by heerhaan** [comment]
En de poep is gefixt
